#pragma once
#include "CObj.h"
#include <tchar.h>

//커맨드 카드 종류
enum class eCommandID
{
	//기본 커맨드
	MOVE = 0,
	STOP = 1,
	ATTACK = 2,
	PATROL = 3,
	HOLD = 4,
	CANCLE = 5,
	RALLY = 6,
	GATHER = 7,
	REPARI = 8,
	NORMAL_BUILDING = 9,
	ADVANCED_BUILDING = 10,
	// 유닛 아이콘 (10~)
	SCV = 11,
	MARINE = 12,
	MEDIC = 13,
	GHOST = 14,
	FIREBAT = 42,
	VULTURE = 15,
	TANK = 16,
	GOLIATH = 17,
	SIEGE_TANK = 40,
	BATTLECRUISER = 20,
	//건물 아이콘
	COMMAND_CENTER = 22,
	SUPPLY_DEPOT = 23,
	REFINERY = 24,
	BARRACKS = 25,
	ENGINEERING_BAY = 26,
	TURRET = 27,
	ACADEMY = 28,
	BUNKER = 29,
	FACTORY = 30,
	STARPORT = 31,
	SCIENCE_FACILITY = 32,
	ARMORY = 33,
	COMBAT_STATION = 34,
	NUCLEAR_SILO = 35,
	SCIENCE_SECRET = 36,
	SCIENCE_PHYSICS = 37,
	FACTORY_ADDON = 38,
	STARPORT_ADDON = 39,
	//유틸리티 아이콘
	U238 = 44,
	STEAMPACK = 45,
	RESTORATION = 46,
	OPTICAL_FLARE = 47,
	CADUCEUS_REACTOR = 48,
	ATTACK_UPGRADE = 49,
	ARMOR_UPGRADE = 50,
	VEHICLE_ATTACK_UPGRADE = 51,
	VEHICLE_ARMOR_UPGRADE = 52,
	SHIP_ATTACK_UPGRADE = 53,
	SHIP_ARMOR_UPGRADE = 54,
	EMP = 55,
	IRRADIATE = 56,
	TITAN = 57,
	CLOCKING = 58,
	MINE = 62,
	YAMATO = 65,
	COLOSSUS = 66,
	NUCLEAR_MISSILE = 67,
	SCANNER = 72,
	NUCLEAR = 75,

	//프로토스 건물
	NEXUS = 100,
	PYLON = 101,
	ASSIMILATOR = 102,
	GATEWAY,
	FORGE,
	PHOTON_CANNON,
	CYBERNETICS_CORE,
	SHIELD_BATTERY,
	ROBOTICS_FACILITY,
	STARGATE,
	CITADEL_OF_ADUN,
	ROBOTICS_SUPPORT_BAY,
	FLEET_BEACON,
	TEMPLAR_ARCHIVES,
	OBSERVATORY,
	ARBITER_TRIBUNAL,
	//프로토스 유닛
	PROBE,
	ZEALOT,
	DRAGOON,
	HIGH_TEMPLAR,
	DARK_TEMPLAR,
	OBSERVER,
	SHUTTLE,
	REAVER,
	SCOUT, 
	CORSAIR,
	CARRIER,
	ARBITER,
	//프로토스 유틸리티
	MIND_CONTROL,
	FEEDBACK,
	MAELSTROM,
	STORM,
	WRAP,
	HALLUCINATION,
	INTERCEPTOR,
	RECALL,
	ICE,
	RUSH, 
	BLINK,
	LOADING,
	LANDING,

	//저그 유닛
	LAVA,
	DRONE,
	OVERLOAD,
	ZERGLING,
	HYDRALISK,
	MUTALISK,
	SCOURGE,
	QUEEN,
	ULTRALISK,
	DEFILER,
	
	//LBuilding
	HATCHERY,
	LAIR, 
	HIVE,
	COLONY,
	EXTRACTOR,
	SPAWNING_POOL,
	EVOLUTION_CHAMBER,
	HYDRALISK_DEN,
	//ABuilding
	SPIRE,
	BASE_QUEEN,
	BASE_TELPO,
	BASE_ULTRALISK,
	BASE_DEFILER,
	
	NONE = 1000
};

//커맨드 카드 1칸
struct CommandSlot
{
	int slotIndex; // 3 * 3 커맨드 카드 슬롯 인덱스
	eCommandID commandID;
	const TCHAR* iconKey; 
	int hotkey;
	bool clickable; //클릭 가능 여부 
	bool visible; //표시 여부
	bool lock; //잠금 여부 
};

//명령 실행에 필요한 상황 정보
struct CommandContext
{
	Vec2 worldPos;
	//공격, 수리, 치료 같은 대상 지정 커맨드
	CObj* pTarget; 
	//필요시 확장
};